ChristianMurphy/postcss-combine-duplicated-selectors

.babelrc, package.json, src/index.js, test/index.js
=> Handle different whitespace between selectors

package.json, test/.eslintrc.yml, test/index.js
=> Test Macro

package.json, test/.eslintrc.yml
update eslint plugin ava, and remove temporary fix
=> Resolve TODO

test/index.js
=> Test General Sibling Selector

package.json, test/index.js
=> Nesting Selectors

README.md
=> add usage guide to README

src/index.js, test/index.js
=> Support attribute selectors

test/index.js
=> Test pseudo elements and pseudo classes

.eslintignore, .gitignore, README.md, package.json, src/index.js, test/.eslintrc.yml, test/_test-factory.es, test/duplicated-css.js, test/duplicated-extension.js, test/duplicated.js, test/unique-css.js, test/unique-extension.js, test/unique.js
=> Handle different textual order

package.json
add prepublish script to ensure code is always updated before release
=> Prepublish Script

.babelrc, README.md, package.json
also updates eslint depedencies
=> Support usage with postcss-cli

.babelrc, package.json
=> Reduce dev dependencies

.eslintrc.yml, README.md
Recommend using ES6 features supported in Node.js version 4 and above
=> Prefer ES6 features over ES5 equivalent

src/index.js, test/duplicated-css.js
=> Adds support for preserving selectors across media queries.

README.md
Wanting to use this in my project so hoping updating the README will nudge an npm publish along ;)
=> Updates README resolves #59

src/index.js, test/duplicated-properties.js
Proposal for resolve #76 issue
=> Added option for maintain or delete duplicate css properties

package-lock.json, package.json
=> chore(package): update eslint-config-google to version 0.9.1

src/index.js, test/duplicated-css.js, test/unique-css.js
=> Issue #81: Keyframes with prefix

commitlint.config.js, package-lock.json, package.json
adopt the Angular recommendations for types and formatting in commit messages.
=> chore: adopt conventional commits standard

README.md, package-lock.json, package.json
Add documentation about standards followed by project, and add commitizen to assist with following conventional commits standard.
=> docs: Standards badges

.travis.yml, appveyor.yml, package.json
=> build(npm): re-add support for node version 6

package-lock.json, package.json, src/index.js, test/_test-factory.js
=> fix(package): update postcss-selector-parser to version 3.1.0

package-lock.json, package.json
=> chore(package): update eslint to version 4.15.0

README.md
=> document css media query deduplicator

README.md, package-lock.json, package.json, src/index.js
based off https://evilmartians.com/chronicles/postcss-8-plugin-migration
=> refactor!: migrate to postcss 8 plugin format

test/unique-css.js
Code works as is, but test case cover some newer CSS features which are good to test anyway.
closes #974
=> test: check media query with prefer color, root selector, variable, and oklch

README.md
I wanted to use your nice postcss plugin with vite and it worked very well !
In order to share the really simple configuration, I just propose this little update.
=> docs: add vite usage in README file

src/index.js, test/duplicated-css.js
=> fix: empty @keyframes emitted
